stages:
  - test
  - build

test_webgui:
  stage: test
  image: circleci/node:10-browsers
  cache:
    key: yarn
    paths:
      - qaul-webgui/.yarn
  script:
    - cd qaul-webgui
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run test

build_webgui:
  stage: build
  image: node:10
  cache:
    key: yarn
    paths:
      - qaul-webgui/.yarn
  script:
    - cd qaul-webgui
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run build --prod
  artifacts:
    paths:
      - qaul-webgui/dist/