stages:
  - test
  - build
  - publish

# Build the Rust root on nightly
build:nightly:
  image: rustlang/rust:nightly
  script:
    - cargo build

# Run test suite
test_webgui:
  stage: test
  image: circleci/node:10-browsers
  cache:
    key: yarn
    paths:
      - qaul-webgui/.yarn
  script:
    - cd qaul-webgui
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run test

build_webgui:
  stage: build
  image: node:10
  cache:
    key: yarn
    paths:
      - qaul-webgui/.yarn
  script:
    - cd qaul-webgui
    - yarn install --pure-lockfile --cache-folder .yarn
    - yarn run build --prod
  artifacts:
    paths:
      - qaul-webgui/dist/

publish_webgui:
  stage: publish
  environment:
    name: master
    url: http://qaul.surge.sh/
  only:
    - master
  image: andthensome/alpine-surge-bash
  script:
    - cd qaul-webgui/dist/
    - surge --project . --domain qaul.surge.sh
