[workspace]
members = [

    # qaul.net service library
    "libqaul",
    "libqaul/platform",
    "libqaul/common",

    # http interface
    # "qaul-http",

    # decentralised routing protocol
    "ratman",
    "ratman/identity",
    "ratman/netmod",
    "ratman/diagnostics",
    "ratman/routing-core",

    # A high-level network simulator
    "service-sim",

    # A _low level_ network simulator
    "netmod-sim",

    # Client specific targets
    "clients/linux",
    "clients/linux-cli"
]
