[workspace]
members = [

    # service userspace library
    "qaul-core",
    "qaul-core/platform",
    "qaul-core/common",

    # qaul.net application library
    "qaul",

    # http interface
    "qaul-http",

    # decentralised routing protocol
    "ratman",
    "ratman/netlink",
    "ratman/routing-core",
    "ratman/diagnostics",

    # A high-level network simulator
    "service-sim",

    # A _low level_ network simulator
    "netmod-sim",

    # Client specific crates
    "clients/linux"
]
