[package]
name = "ratman-netmod"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]
identity = { path = "../identity", package = "ratman-identity" }