[package]
name = "ratman"
description = "A fully delay tolerant, decentralised userspace routing protocol"
license = "GPL-3.0"
version = "0.0.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]

# Sub-components
routing-core = { path = "routing-core", package = "ratman-routing-core" }
diagnostics = { path = "diagnostics", package = "ratman-diagnostics" }
identity = { path = "identity", package = "ratman-identity" }
netmod = { path = "netmod", package = "ratman-netmod"}