[package]
name = "qaul-common"
description = "A collection of common types and abstractons shared across all qaul.net libraries"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]