[package]
name = "qaul-http"
version = "0.1.0"
authors = ["Jess 3Jane <me@jess.coffee>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
iron = "0.6"
persistent = "0.4"

libqaul = { path = ".." } 
