[package]
name = "libqaul"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]
edition = "2018"

[dependencies]

# libqaul internal dependencies
common = { path = "common", package = "qaul-common" }
storage = { path = "storage", package = "qaul-storage" }
platform = { path = "platform", package = "qaul-platform" }